/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;

import com.geeks.beans.UserBean;
import javax.swing.JFrame;

/**
 *
 * @author khatr
 */
public class ParkDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ParkDashboard
     */
    private UserBean userBean;
    public ParkDashboard(UserBean userBean) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.userBean = userBean;
        userLbl.setText(userBean.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageBtn = new javax.swing.JButton();
        userLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        ticketBtn = new javax.swing.JButton();
        viewBookingBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1360, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        packageBtn.setBorder(null);
        packageBtn.setBorderPainted(false);
        packageBtn.setContentAreaFilled(false);
        packageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        packageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageBtnActionPerformed(evt);
            }
        });
        getContentPane().add(packageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 280, 190));

        userLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLbl.setForeground(new java.awt.Color(64, 38, 28));
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 30));

        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 280, 80));

        ticketBtn.setBorder(null);
        ticketBtn.setBorderPainted(false);
        ticketBtn.setContentAreaFilled(false);
        ticketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ticketBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 280, 190));

        viewBookingBtn.setBorder(null);
        viewBookingBtn.setBorderPainted(false);
        viewBookingBtn.setContentAreaFilled(false);
        viewBookingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, 280, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 38, 28));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/geeks/icons/WaterPark Dashboard – 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void packageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageBtnActionPerformed
        new PackageFrame(userBean).setVisible(true);
        dispose();
    }//GEN-LAST:event_packageBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new MainDashboard(userBean).setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void ticketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketBtnActionPerformed
        new TicketFrame(userBean).setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketBtnActionPerformed

    private void viewBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookingBtnActionPerformed
        new ViewTicketBookings(userBean).setVisible(true);
        dispose();
    }//GEN-LAST:event_viewBookingBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton packageBtn;
    private javax.swing.JButton ticketBtn;
    private javax.swing.JLabel userLbl;
    private javax.swing.JButton viewBookingBtn;
    // End of variables declaration//GEN-END:variables
}
